"""add oauth fields

Revision ID: 00672c280fe1
Revises: 874a7bd89b09
Create Date: 2026-05-29 22:21:48.932273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00672c280fe1'
down_revision = '874a7bd89b09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('google_id', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['google_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('google_id')
        batch_op.drop_column('provider')

    # ### end Alembic commands ###
